services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
      - action: sync
        path: ./backend
        target: ./
        ignore:
          - node_modules/
          - tests/

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
